# Generated by Django 3.1.7 on 2021-02-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20210228_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='tags',
        ),
    ]
